// language supported by DeepL API: https://developers.deepl.com/docs/getting-started/supported-languages
export const LANGUAGES = [
  { code: "AF", name: "Afrikaans" },
  { code: "SQ", name: "Albanian" },
  { code: "AR", name: "Arabic" },
  { code: "HY", name: "Armenian" },
  { code: "AZ", name: "Azerbaijani" },
  { code: "EU", name: "Basque" },
  { code: "BE", name: "Belarusian" },
  { code: "BN", name: "Bengali" },
  { code: "BS", name: "Bosnian" },
  { code: "BG", name: "Bulgarian" },
  { code: "MY", name: "Burmese" },
  { code: "CA", name: "Catalan" },
  { code: "ZH-HANS", name: "Chinese (Simplified)" },
  { code: "ZH-HANT", name: "Chinese (Traditional)" },
  { code: "HR", name: "Croatian" },
  { code: "CS", name: "Czech" },
  { code: "DA", name: "Danish" },
  { code: "NL", name: "Dutch" },
  { code: "EN-GB", name: "English (British)" },
  { code: "EN-US", name: "English (American)" },
  { code: "EO", name: "Esperanto" },
  { code: "ET", name: "Estonian" },
  { code: "FI", name: "Finnish" },
  { code: "FR", name: "French" },
  { code: "FR-CA", name: "French (Canadian)" },
  { code: "GL", name: "Galician" },
  { code: "KA", name: "Georgian" },
  { code: "DE", name: "German" },
  { code: "DE-CH", name: "German (Swiss)" },
  { code: "EL", name: "Greek" },
  { code: "GU", name: "Gujarati" },
  { code: "HT", name: "Haitian Creole" },
  { code: "HA", name: "Hausa" },
  { code: "HE", name: "Hebrew" },
  { code: "HI", name: "Hindi" },
  { code: "HU", name: "Hungarian" },
  { code: "IS", name: "Icelandic" },
  { code: "ID", name: "Indonesian" },
  { code: "GA", name: "Irish" },
  { code: "IT", name: "Italian" },
  { code: "JA", name: "Japanese" },
  { code: "KK", name: "Kazakh" },
  { code: "KO", name: "Korean" },
  { code: "KY", name: "Kyrgyz" },
  { code: "LA", name: "Latin" },
  { code: "LV", name: "Latvian" },
  { code: "LT", name: "Lithuanian" },
  { code: "MK", name: "Macedonian" },
  { code: "MS", name: "Malay" },
  { code: "ML", name: "Malayalam" },
  { code: "MT", name: "Maltese" },
  { code: "MR", name: "Marathi" },
  { code: "MN", name: "Mongolian" },
  { code: "NE", name: "Nepali" },
  { code: "NB", name: "Norwegian" },
  { code: "FA", name: "Persian" },
  { code: "PL", name: "Polish" },
  { code: "PT-BR", name: "Portuguese (Brazilian)" },
  { code: "PT-PT", name: "Portuguese (European)" },
  { code: "PA", name: "Punjabi" },
  { code: "RO", name: "Romanian" },
  { code: "RU", name: "Russian" },
  { code: "SR", name: "Serbian" },
  { code: "SK", name: "Slovak" },
  { code: "SL", name: "Slovenian" },
  { code: "ES", name: "Spanish" },
  { code: "ES-419", name: "Spanish (Latin American)" },
  { code: "SW", name: "Swahili" },
  { code: "SV", name: "Swedish" },
  { code: "TL", name: "Tagalog" },
  { code: "TA", name: "Tamil" },
  { code: "TE", name: "Telugu" },
  { code: "TH", name: "Thai" },
  { code: "TR", name: "Turkish" },
  { code: "UK", name: "Ukrainian" },
  { code: "UR", name: "Urdu" },
  { code: "UZ", name: "Uzbek" },
  { code: "VI", name: "Vietnamese" },
  { code: "CY", name: "Welsh" },
  { code: "ZU", name: "Zulu" },
] as const;

export type SupportedLanguageCode = (typeof LANGUAGES)[number]["code"];